// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gestor-sidebar/GestorSidebar.tsx": () => import("../components/mockups/gestor-sidebar/GestorSidebar.tsx")
};
